Repository programmfabrik/fylr-helm, pull requests merged in 2022-11, with the labels that each got.

#6 feature: added fylr helm chart deployment files
  .github/workflows/helm_fylr_tests.yml
  Makefile
  README.md
  charts/fylr/.helmignore
  charts/fylr/Chart.lock
  charts/fylr/Chart.yaml
  charts/fylr/README.md
  charts/fylr/charts/elasticsearch-19.4.2.tgz
  charts/fylr/charts/execserver-0.1.1.tgz
  charts/fylr/charts/minio-4.0.14.tgz
  charts/fylr/charts/postgresql-ha-9.4.6.tgz
  charts/fylr/templates/NOTES.txt
  charts/fylr/templates/_helpers.tpl
  charts/fylr/templates/configmap.yaml
  charts/fylr/templates/deployment.yaml
  charts/fylr/templates/hpa.yaml
  charts/fylr/templates/ingress.yaml
  charts/fylr/templates/persistentVolumeClaim.yaml
  charts/fylr/templates/prometheus.yaml
  charts/fylr/templates/secrets.yaml
  charts/fylr/templates/service.yaml
  charts/fylr/templates/serviceaccount.yaml
  charts/fylr/templates/tests/test-connection.yaml
  charts/fylr/values.yaml
Labels: feature, size/XXL

#17 fix: fylr generated disk block volume ident
  charts/fylr/Chart.yaml
  charts/fylr/templates/_helpers.tpl
Labels: fix, size/XS

#16 Update README.md
  charts/fylr/README.md
Labels: size/XS
